# Generated by Django 4.2.13 on 2024-06-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_underscore',
            new_name='profile_pic',
        ),
    ]
